CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER IF NOT EXISTS 'wordpress'@'%' IDENTIFIED BY 'StrongPassword123';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER
    ON wordpress.*
    TO 'wordpress'@'%';

FLUSH PRIVILEGES;
